### ISSUE TITLE
Undeclared dependency on IO::Socket::SSL

### ISSUE THREAD

**Issue by andk** [upwork/perl-upwork#2]
As per subject. Grep:
http://search.cpan.org/grep?release=Net-Upwork-API-1.1.0;string=IO::Socket::SSL;n=1;C=0
Sample fail report:
http://www.cpantesters.org/cpan/report/60941486
Overview:
http://matrix.cpantesters.org/?dist=Net-Upwork-API%201.1.0

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by mnovozhylov** [comment]
@andk , thanks!
should be fixed in https://github.com/upwork/perl-upwork/commit/1b447f5e565c99c065fe559535c4274f686f3176
